"""empty message

Revision ID: 47b4b9602875
Revises: 9cd711bbe9f4
Create Date: 2020-05-21 22:04:38.275524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b4b9602875'
down_revision = '9cd711bbe9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_goal', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_goal', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
