"""empty message

Revision ID: 67d185d16a9f
Revises: feebd26b4918
Create Date: 2020-04-23 08:39:32.645789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d185d16a9f'
down_revision = 'feebd26b4918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(), nullable=True),
    sa.Column('full', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('activity', sa.String(), nullable=True))
    op.add_column('users', sa.Column('group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('university_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university_id')
    op.drop_column('users', 'group')
    op.drop_column('users', 'activity')
    op.drop_table('user_contacts')
    op.drop_table('university')
    # ### end Alembic commands ###
