"""empty message

Revision ID: 6b4c1ab64ecf
Revises: 4434247efc72
Create Date: 2020-06-15 11:13:30.628226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4c1ab64ecf'
down_revision = '4434247efc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_goal', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_column('challenge_goal', 'point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_goal', sa.Column('point', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('challenge_goal', 'score')
    # ### end Alembic commands ###
